themes/mlibrary/css/omeka-mlibrary.css
themes/mlibrary/custom.php
themes/mlibrary/exhibit-builder/exhibits/summary.php

This is the Introduction page which will show an image from each parent page and a snippet of text from the page. The is a link that takes the user to the page. The information for Card will be themed with the new theming developed by Bridget.

Create themes in exhibit introductionpage-61

---

plugins/ExhibitBuilder/helpers/ExhibitFunctions.php
themes/mlibrary_new/css/style.css
themes/mlibrary_new/custom.php
themes/mlibrary_new/exhibit-builder/exhibits/browse.php
themes/mlibrary_new/exhibit-builder/exhibits/card.php
themes/mlibrary_new/exhibit-builder/exhibits/single.php
themes/mlibrary_new/functions.php
themes/mlibrary_new/index.php

to view changes for homepage https://nancymou.www.lib.umich.edu/online-exhibits-2.3/
Browse exhibits is not finished, just created in this pull request

update the home page to display feature exhibit and 4 recent exhibits

---

themes/mlibrary/custom.php
themes/mlibrary_new/common/header.php
themes/mlibrary_new/config.ini
themes/mlibrary_new/custom.php
themes/mlibrary_new/exhibit-builder/exhibits/browse.php
themes/mlibrary_new/exhibit-builder/exhibits/summary.php
themes/mlibrary_new/exhibit-builder/exhibits/tags.php
themes/mlibrary_new/index.php
themes/mlibrary_new/search/index.php

Changes on Browse, Header, tags and custom files

Browse page

---

themes/mlibrary_new/common/footer.php

Remove theme specific footer addition.
Add library copyright text and link.

Add copyright to footer

---

themes/mlibrary_new/exhibit-builder/exhibits/summary.php

I noticed these while reviewing another PR.  The space before the 12 looked like a typo.

Fix a suspected typo.

---

themes/mlibrary_new/common/header.php
themes/mlibrary_new/css/style.css
themes/mlibrary_new/functions.php

Also move an inline style to the style.css.

Consolidate header background image logic

---

themes/mlibrary_new/css/style.css
themes/mlibrary_new/exhibit-builder/exhibits/show.php

Initial UI work for Exhibit Show page #111

---

themes/mlibrary_new/common/header.php

Put Browse and About into the nav list as requested.

Update header nav list.

---

themes/mlibrary_new/css/style.css
themes/mlibrary_new/exhibit-builder/exhibits/show.php
themes/mlibrary_new/search/search-form.php

- Update show page layout (fixes #132 )
- Update show page section nav panels (image dimensions and semantics)
- Lite cleanup CSS/eliminated image card redundancy/group media queries

Show page layout

---

themes/mlibrary_new/search/search-form.php

-Fix a11y violation in Search form.

Fix a11y issue in Search form

---

themes/mlibrary_new/custom.php
themes/mlibrary_new/exhibit-builder/exhibits/gallery.php
themes/mlibrary_new/exhibit-builder/exhibits/show.php
themes/mlibrary_new/exhibit-builder/exhibits/summary.php

Add code to display images in section and subsection.
The style is not finished yet.

Gallery page

---

themes/mlibrary_new/css/style.css
themes/mlibrary_new/custom.php
themes/mlibrary_new/exhibit-builder/exhibits/gallery.php

Beginning Gallery UI for sprint review. Still styling left.

Gallery UI

---

themes/mlibrary_new/exhibit-builder/exhibits/gallery.php

Still need to look at getting the section title above the image group.
For #149

Fixes missing images

---

themes/mlibrary_new/css/style.css
themes/mlibrary_new/exhibit-builder/exhibits/gallery.php
themes/mlibrary_new/exhibit-builder/exhibits/show.php
themes/mlibrary_new/theme.ini

Finishes Show #118

---

themes/mlibrary_new/exhibit-builder/exhibits/summary.php

Remove the Gallery card from the summary page
#168

update the summary page to stop show the gallery card

---

themes/mlibrary_new/exhibit-builder/exhibits/gallery.php

Add title for each section in gallery page

add title of each section

---

themes/mlibrary_new/common/footer.php

update date at footer

---

themes/mlibrary_new/css/style.css
themes/mlibrary_new/custom.php
themes/mlibrary_new/exhibit-builder/exhibits/browse.php
themes/mlibrary_new/exhibit-builder/exhibits/gallery.php
themes/mlibrary_new/exhibit-builder/exhibits/show.php
themes/mlibrary_new/exhibit-builder/exhibits/summary.php
themes/mlibrary_new/exhibit-builder/exhibits/tags.php

Ran a light review of the index, summary, show, browse, and gallery pages. Did the quick fixes for the current sprint, including updating flagged semantics.

A11y fixes for Sprint 9

---

themes/mlibrary_new/custom.php
themes/mlibrary_new/exhibit-builder/exhibits/gallery.php

Add the item title to alt for all images
Remove caption from the Gallery page.
Some images have alt is null because those they are decorative images.
#154

Add title to alt for all images.

---

themes/mlibrary_new/custom.php

Link Gallery cards with item file.
#154

Add url to the cards in the gallery

---

themes/mlibrary_new/custom.php

support video with new theme

---

themes/mlibrary_new/css/style.css
themes/mlibrary_new/index.php

- update number of images displaying in featured on index page
- update gallery styling (height, border)

Update index columns and gallery styling

---

themes/mlibrary_new/css/style.css
themes/mlibrary_new/simple-pages/page/about.php

UI for About page
Add fix for focus

UI for About page and a11y fix

---

themes/mlibrary_new/custom.php

Remove comments
Fix alt in cards in summary page.

remove comments, add alt to video image in the exhibit layout page

---

themes/mlibrary_new/items/show.php

Start item page + add footer

---

themes/mlibrary_new/custom.php

Use the class image-card for all <img>

use image-card class

---

online-exhibit-patches/ExhibitLayout.patch

Update the Exhibit Layout default

change the Exhibit layout default

---

plugins/ExhibitGalleryPage/ExhibitGalleryPagePlugin.php
themes/mlibrary_new/search/index.php

Update the Gallery plugin to check if the gallery page exists before added.
Remove text from the search page

Exhibit description search page

---

plugins/Cosign/CosignPlugin.php
plugins/Cosign/controllers/CosignController.php

[Issue 133](https://github.com/mlibrary/online-exhibits/issues/133)

Fix for /admin/ and apply Zend coding style

---

themes/mlibrary_new/custom.php
themes/mlibrary_new/exhibit-builder/exhibits/gallery.php
themes/mlibrary_new/items/show.php

Uninstall Zoom plugin.
Add a condition to item page to display image and metadata when item page accessed from admin site, not from Exhibit or Gallery page.

M library remove old zoom

---

themes/mlibrary_new/common/header.php
themes/mlibrary_new/css/style.css
themes/mlibrary_new/items/show.php

Beginning style and layout for the new item page. Will tweak after testing on beta.

UI - Item page styling/layout

---

themes/mlibrary_new/items/show.php

stop display navigation if item page accessed from the admin site

stop display navigation if item page accessed from the admin site

---

plugins/Iiif/controllers/IiifController.php

* The GD library can't open some types of files, so check for a derivative.
* If there is a derivative for the image, use that first.
* Cleanup: Make `constructPath()` a static function.
* Don't reuse the `$file` variable in `getPath()`.
If we need more robust image manipulation look into the php imagick extension.

243 Fix errors in iiif caused by .tif or .tiff images

---

plugins/Access/AccessPlugin.php

Redirect all forms under items to home page except show page

---

plugins/Access/AccessPlugin.php

Change route of collections to home page

---

plugins/RedirectingByRoutes/RedirectingByRoutes.php
plugins/RedirectingByRoutes/plugin.ini

This plugin will redirect pages using Router Zend class

Add Redirect by Routes plugin

---

themes/mlibrary_new/custom.php
themes/mlibrary_new/items/show.php

Add a `return` parameter to item links in gallery pages so that item pages can return to gallery pages.

Restore functionality for the return link

---

themes/mlibrary_new/exhibit-builder/exhibits/gallery.php
themes/mlibrary_new/items/show.php

Update the item page with Ux modification requested for breadcrumb and back button.
update the gallery page with Ux changes requested for making all labels "Gallery" instead of Exhibit image Gallery.
issue #266

Update the item page 

---

themes/mlibrary_new/common/header.php
themes/mlibrary_new/exhibit-builder/exhibits/gallery.php
themes/mlibrary_new/exhibit-builder/exhibits/show.php
themes/mlibrary_new/exhibit-builder/exhibits/summary.php
themes/mlibrary_new/items/show.php

Update the breadcrumb

---

themes/mlibrary_new/common/header.php
themes/mlibrary_new/css/style.css
themes/mlibrary_new/items/show.php

Updates to item page.
Update styling and layout for breadcrumbs on item page and other pages.

Update item page and breadcrumbs

---

themes/mlibrary_new/common/header.php
themes/mlibrary_new/css/style.css
themes/mlibrary_new/exhibit-builder/exhibits/browse.php
themes/mlibrary_new/exhibit-builder/exhibits/gallery.php
themes/mlibrary_new/exhibit-builder/exhibits/show.php
themes/mlibrary_new/exhibit-builder/exhibits/summary.php
themes/mlibrary_new/index.php
themes/mlibrary_new/items/browse.php
themes/mlibrary_new/items/show.php
themes/mlibrary_new/items/single.php
themes/mlibrary_new/simple-pages/page/about.php

Update the Title and Credit for the Exhibition summary page. Had to update the container class across the site in order for the background to be a white for that row.

268 Update Exhibit title introduction and containers across site

---

themes/mlibrary_new/exhibit-builder/exhibits/browse.php

Add link, exhibit URL, to square thumbnail images in browse page.
issue #283

Add link to images

---

plugins/Iiif/controllers/IiifController.php
plugins/Iiif/vendor/conlect/image-iiif/src/ImageIIIF.php

Use imagick if available.  Don't try to render pdfs.

---

plugins/BlogLayout/views/shared/exhibit_layouts/double-image/layout.css
plugins/BlogLayout/views/shared/exhibit_layouts/single-image/layout.css
themes/mlibrary_new/css/style.css

Update layout for double images in blog layout. Solves #241

#241 Fix double image layout

---

themes/mlibrary_new/common/header.php
themes/mlibrary_new/css/style.css
themes/mlibrary_new/exhibit-builder/exhibits/browse.php
themes/mlibrary_new/exhibit-builder/exhibits/gallery.php
themes/mlibrary_new/exhibit-builder/exhibits/show.php
themes/mlibrary_new/exhibit-builder/exhibits/summary.php
themes/mlibrary_new/index.php
themes/mlibrary_new/items/browse.php
themes/mlibrary_new/items/show.php
themes/mlibrary_new/items/single.php
themes/mlibrary_new/search/index.php
themes/mlibrary_new/simple-pages/page/about.php

Updating layout, adding vendor prefixes for grid, and adding fixes for mobile view. 
Still have some final touches to come.

Updates for mobile fixes and layout updates

---

themes/mlibrary_new/common/footer.php

Add twitter script

---

themes/mlibrary_new/search/index.php

Add default image and url for exhibits without cover image and url

---

themes/mlibrary_new/exhibit-builder/exhibits/browse.php

Add filter summary to the first part of issue #292

Add filterSummary message to browse page

---

themes/mlibrary_new/exhibit-builder/exhibits/browse.php

Add a Browse all link to rest the filter issue #292

Add Browse all link to reset the filter

---

themes/mlibrary_new/config.ini

Remove the option of feature the exhibit from the config file. It is available at the exhibit level

Clean up config file

---

plugins/ReassignOwnership/ReassignOwnershipPlugin.php

Update the plugin to apply new owner to all items that belong to the collection with the new owner.
solve #240

Change items belong to collection

---

themes/mlibrary_new/common/header.php

fix a typo in the header back ground in the home page

---

themes/mlibrary_new/exhibit-builder/exhibits/single.php
themes/mlibrary_new/search/index.php

Assign null to alt

---

themes/mlibrary_new/exhibit-builder/exhibits/card.php
themes/mlibrary_new/exhibit-builder/exhibits/single.php

Update the card and feature exhibit in the homepage to have one link for the image and text.

Update the card and feature exhibit in homepage to have one link

---

themes/mlibrary_new/search/index.php

set alt to null for images and remove the link from images

---

.env-example
.gitignore
Dockerfile
auth_openidc.conf
compose.yml

Copied from call-number-mapping primarily.  Nothing too original here. Nothing lives at / for this one, everything's /online-exhibits/.

Adding a compose.yml and Dockerfile and openidc
